# Generated by Django 4.0.6 on 2022-07-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='username',
            new_name='email',
        ),
    ]
